version: 0.0
os: linux
files:
  - source: /
    destination: /home/biden
  - source: /bidenbot-discord.service
    destination: /etc/systemd/system
  - source: /bidenbot-slack.service
    destination: /etc/systemd/system
permissions:
  - object: /home/biden
    owner: biden
    group: biden
  - object: /etc/systemd/system/bidenbot-discord.service
    owner: root
    group: root
  - object: /etc/systemd/system/bidenbot-slack.service
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: hooks/beforeInstall.sh
      runas: root
  AfterInstall:
    - location: hooks/afterInstall.sh
      runas: root
  ApplicationStart:
    - location: hooks/appStart.sh
      runas: root
#  ApplicationStop:
#    - location: hooks/appStop.sh
#      runas: root
