steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/kubots/bidenbot/discord:latest', '.', '-f', 'discord.Dockerfile' ]
images:
- 'us-central1-docker.pkg.dev/kubots/bidenbot/discord:latest'