# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidenbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bidenbot
  template:
    metadata:
      labels:
        app: bidenbot
    spec:
      containers:
        - name: bidenbot-discord
          # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
          # Replace $GCLOUD_PROJECT with your project ID.
          image: us-central1-docker.pkg.dev/kubots/bidenbot/discord:latest
          # This app listens on port 8080 for web traffic by default.
          resources:
            requests:
              cpu: "0.1"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: discord_token
            - name: SPLUNK_OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_SERVICE_NAME
              value: "bidenbot-discord"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://${SPLUNK_OTEL_AGENT}:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=prod"
